export const GET_MEMBER_CORE_DETAILS = "GET_MEMBER_CORE_DETAILS";

export const GET_LOGGED_IN_MEMBER_DETAILS = "GET_LOGGED_IN_MEMBER_DETAILS"; 

export const EDIT_LOGGED_IN_MEMBER = "EDIT_LOGGED_IN_MEMBER";

export const RESET_MEMBER_STORE_DETAILS = "RESET_MEMBER_STORE_DETAILS";