export const GET_PROJECT_BASIC_DETAILS = "GET_PROJECT_BASIC_DETAILS";

export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT"; 

export const GET_PROJECT_CORE_DETAILS = "GET_PROJECT_CORE_DETAILS"; 

export const EDIT_PROJECT = "EDIT_PROJECT"; 

export const ASSIGN_PROJECTS = "ASSIGN_PROJECTS"; 

export const ASSIGN_PROJECTS_TO_MEMBER = "ASSIGN_PROJECTS_TO_MEMBER"; 

