export const GET_PROJECT_BASIC_DETAILS = "GET_PROJECT_BASIC_DETAILS";

export const ADD_NEW_PROJECT = "ADD_NEW_PROJECT"; 

export const GET_PROJECT_CORE_DETAILS = "GET_PROJECT_CORE_DETAILS"; 

export const EDIT_PROJECT = "EDIT_PROJECT"; 

export const ASSIGN_PROJECTS = "ASSIGN_PROJECTS"; 

export const ASSIGN_PROJECTS_TO_MEMBER = "ASSIGN_PROJECTS_TO_MEMBER";   

export const GET_TEAM_PROJECTS = "GET_TEAM_PROJECTS"; 

export const GET_MEMBER_PROJECTS = "GET_MEMBER_PROJECTS"; 

export const UPDATE_PROJECT_STATUS = "UPDATE_PROJECT_STATUS"; 

export const REMOVE_MEMBER_FROM_PROJECT = "REMOVE_MEMBER_FROM_PROJECT"; 

export const RESET_PROJECT_STORE_DETAILS = "RESET_PROJECT_STORE_DETAILS"; 
