export const GET_ALL_TEAMS_BASIC_DETAILS = "GET_ALL_TEAMS_BASIC_DETAILS";

export const ADD_NEW_TEAM = "ADD_NEW_TEAM";

export const GET_TEAM_CORE_DETAILS = "GET_TEAM_CORE_DETAILS";

export const GET_ALL_MEMBERS_BASIC_DETAILS = "GET_ALL_MEMBERS_BASIC_DETAILS";

export const GET_MEMBER_CORE_DETAILS = "GET_MEMBER_CORE_DETAILS";

export const TEAM_NAMES_FOR_NEW_MEMBER = "TEAM_NAMES_FOR_NEW_MEMBER";

export const ADD_NEW_MEMBER = "ADD_NEW_MEMBER"; 

export const DELETE_MEMBER = "DELETE_MEMBER";

export const EDIT_MEMBER = "EDIT_MEMBER";

