export const GET_ALL_TEAMS_BASIC_DETAILS = "GET_ALL_TEAMS_BASIC_DETAILS";

export const ADD_NEW_TEAM = "ADD_NEW_TEAM";

export const GET_TEAM_CORE_DETAILS = "GET_TEAM_CORE_DETAILS";

export const GET_ALL_MEMBERS_BASIC_DETAILS = "GET_ALL_MEMBERS_BASIC_DETAILS";

export const GET_MEMBER_CORE_DETAILS = "GET_MEMBER_CORE_DETAILS";

export const ADD_NEW_MEMBER = "ADD_NEW_MEMBER";


